#pragma once

#include <pebble.h>

#define NOW 0

#ifdef PBL_PLATFORM_EMERY
#define RAINBOW_HAND_OFFSET_X 5
#define RAINBOW_HAND_OFFSET_Y 81
#define TIME_CONFLICT_OFFSET 10
#define TICK_WIDTH 2
#define HOUR_HAND_WIDTH 8
#define MINUTE_HAND_WIDTH 8
#define CENTER_CIRCLE_RADIUS 7
#define MINUTE_HAND_RADIUS 78
#define HOUR_HAND_RADIUS 58
#elif PBL_ROUND
#define RAINBOW_HAND_OFFSET_X 5
#define RAINBOW_HAND_OFFSET_Y 55
#define TIME_CONFLICT_OFFSET 10
#define TICK_WIDTH 2
#define HOUR_HAND_WIDTH 6
#define MINUTE_HAND_WIDTH 6
#define CENTER_CIRCLE_RADIUS 5
#define MINUTE_HAND_RADIUS 52
#define HOUR_HAND_RADIUS 39
#else
#define RAINBOW_HAND_OFFSET_X 5
#define RAINBOW_HAND_OFFSET_Y 55
#define TIME_CONFLICT_OFFSET 10
#define TICK_WIDTH 2
#define HOUR_HAND_WIDTH 6
#define MINUTE_HAND_WIDTH 6
#define CENTER_CIRCLE_RADIUS 5
#define MINUTE_HAND_RADIUS 52
#define HOUR_HAND_RADIUS 39
#endif
